apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mini-project
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # base64("password")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mini-project
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mini-project
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
