name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        # Update Deployment images
        kubectl set image deployment/frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -n mini-project
        kubectl set image deployment/backend backend=${{ secrets.DOCKERHUB_USERNAME }}/backend:latest -n mini-project
        
        # Apply manifests (if new resources or updates)
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/ingress.yaml
