name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Frontend Image
      run: |
        docker build -t frontend-local:latest ./frontend
        minikube image load frontend-local:latest

    - name: Build Backend Image
      run: |
        docker build -t backend-local:latest ./backend
        minikube image load backend-local:latest

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/ingress.yaml
